export interface EndpointDefinition {
  key: string
  method: "GET" | "POST"
  path: string
  kind: "json" | "download"
  description: string
  pagination?: {
    enabled: true
    maxPageSize: number
  }
}

export const ENDPOINTS: Record<string, EndpointDefinition> = {
  // ─── auth ───
  "auth.login": {
    key: "auth.login",
    method: "POST",
    path: "/application/auth/oauth/open/loginV2",
    kind: "json",
    description: "Get access token",
  },

  // ─── lookup (served from local data, not HTTP) ───
  "lookup.research-areas.list": {
    key: "lookup.research-areas.list",
    method: "GET",
    path: "/guide/research-area-local",
    kind: "json",
    description: "List research areas from local docs",
  },
  "lookup.broker-orgs.list": {
    key: "lookup.broker-orgs.list",
    method: "GET",
    path: "/guide/broker-orgs-local",
    kind: "json",
    description: "List broker orgs from local docs",
  },
  "lookup.meeting-orgs.list": {
    key: "lookup.meeting-orgs.list",
    method: "GET",
    path: "/guide/meeting-orgs-local",
    kind: "json",
    description: "List meeting orgs from local docs",
  },
  "lookup.industries.list": {
    key: "lookup.industries.list",
    method: "GET",
    path: "/guide/industries-local",
    kind: "json",
    description: "List industries from local docs",
  },
  "lookup.regions.list": {
    key: "lookup.regions.list",
    method: "GET",
    path: "/guide/regions-local",
    kind: "json",
    description: "List regions from local docs",
  },
  "lookup.announcement-categories.list": {
    key: "lookup.announcement-categories.list",
    method: "GET",
    path: "/guide/announcement-categories-local",
    kind: "json",
    description: "List announcement categories from local docs",
  },
  "lookup.industry-codes.list": {
    key: "lookup.industry-codes.list",
    method: "GET",
    path: "/guide/industry-codes-local",
    kind: "json",
    description: "List Shenwan industry codes from local docs",
  },
  "lookup.theme-ids.list": {
    key: "lookup.theme-ids.list",
    method: "GET",
    path: "/guide/theme-ids-local",
    kind: "json",
    description: "List theme IDs from local docs",
  },

  // ─── insight ───
  "insight.opinion.list": {
    key: "insight.opinion.list",
    method: "POST",
    path: "/application/open-insight/chief-opinion/getList",
    kind: "json",
    description: "List domestic institution chief opinions",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.summary.list": {
    key: "insight.summary.list",
    method: "POST",
    path: "/application/open-insight/summary/v2/getList",
    kind: "json",
    description: "List summaries",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.summary.download": {
    key: "insight.summary.download",
    method: "GET",
    path: "/application/open-insight/summary/v2/download/file",
    kind: "download",
    description: "Download summary file",
  },
  "insight.roadshow.list": {
    key: "insight.roadshow.list",
    method: "POST",
    path: "/application/open-insight/schedule/roadshow/getList",
    kind: "json",
    description: "List roadshows",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.site-visit.list": {
    key: "insight.site-visit.list",
    method: "POST",
    path: "/application/open-insight/schedule/site-visit/getList",
    kind: "json",
    description: "List site visits",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.strategy.list": {
    key: "insight.strategy.list",
    method: "POST",
    path: "/application/open-insight/schedule/strategy-meeting/getList",
    kind: "json",
    description: "List strategy meetings",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.forum.list": {
    key: "insight.forum.list",
    method: "POST",
    path: "/application/open-insight/schedule/forum/getList",
    kind: "json",
    description: "List forums",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.research.list": {
    key: "insight.research.list",
    method: "POST",
    path: "/application/open-insight/broker-report/getList",
    kind: "json",
    description: "List broker research reports",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.research.download": {
    key: "insight.research.download",
    method: "GET",
    path: "/application/open-insight/broker-report/download/file",
    kind: "download",
    description: "Download broker research report",
  },
  "insight.foreign-report.list": {
    key: "insight.foreign-report.list",
    method: "POST",
    path: "/application/open-insight/foreign-report/getList",
    kind: "json",
    description: "List foreign reports",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.foreign-report.download": {
    key: "insight.foreign-report.download",
    method: "GET",
    path: "/application/open-insight/foreign-report/download/file",
    kind: "download",
    description: "Download foreign report",
  },
  "insight.announcement.list": {
    key: "insight.announcement.list",
    method: "POST",
    path: "/application/open-insight/announcement/getList",
    kind: "json",
    description: "List A-share announcements",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.announcement.download": {
    key: "insight.announcement.download",
    method: "GET",
    path: "/application/open-insight/announcement/download/file",
    kind: "download",
    description: "Download A-share announcement file",
  },
  "insight.announcement-hk.list": {
    key: "insight.announcement-hk.list",
    method: "POST",
    path: "/application/open-insight/announcement-hk/getList",
    kind: "json",
    description: "List HK announcements",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.announcement-hk.download": {
    key: "insight.announcement-hk.download",
    method: "GET",
    path: "/application/open-insight/announcement-hk/download/file",
    kind: "download",
    description: "Download HK announcement file",
  },
  "insight.foreign-opinion.list": {
    key: "insight.foreign-opinion.list",
    method: "POST",
    path: "/application/open-insight/foreign-opinion/getList",
    kind: "json",
    description: "List foreign institution opinions",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.independent-opinion.list": {
    key: "insight.independent-opinion.list",
    method: "POST",
    path: "/application/open-insight/independent-opinion/getList",
    kind: "json",
    description: "List foreign independent analyst opinions",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "insight.independent-opinion.download": {
    key: "insight.independent-opinion.download",
    method: "GET",
    path: "/application/open-insight/independent-opinion/download/file",
    kind: "download",
    description: "Download foreign independent opinion file",
  },

  // ─── reference ───
  "reference.securities-search": {
    key: "reference.securities-search",
    method: "POST",
    path: "/application/open-reference/securities/search",
    kind: "json",
    description: "Search GTS codes (securities)",
  },

  // ─── quote ───
  "quote.day-kline": {
    key: "quote.day-kline",
    method: "POST",
    path: "/application/open-quote/kline/daily",
    kind: "json",
    description: "Query A-share daily kline (SH/SZ/BJ)",
  },
  "quote.day-kline-hk": {
    key: "quote.day-kline-hk",
    method: "POST",
    path: "/application/open-quote/kline-hk/daily",
    kind: "json",
    description: "Query HK stock daily kline (HK)",
  },
  "quote.index-day-kline": {
    key: "quote.index-day-kline",
    method: "POST",
    path: "/application/open-quote/index/kline/daily",
    kind: "json",
    description: "Query SH/SZ/BJ index daily kline",
  },
  "quote.minute-kline": {
    key: "quote.minute-kline",
    method: "POST",
    path: "/application/open-quote/kline/minute",
    kind: "json",
    description: "Query A-share minute kline (SH/SZ/BJ)",
  },

  // ─── fundamental ───
  "fundamental.income-statement": {
    key: "fundamental.income-statement",
    method: "POST",
    path: "/application/open-fundamental/financial-report/income-statement/accumulated",
    kind: "json",
    description: "Query income statement (accumulated)",
  },
  "fundamental.income-statement-quarterly": {
    key: "fundamental.income-statement-quarterly",
    method: "POST",
    path: "/application/open-fundamental/financial-report/income-statement/quarterly",
    kind: "json",
    description: "Query income statement (quarterly)",
  },
  "fundamental.balance-sheet": {
    key: "fundamental.balance-sheet",
    method: "POST",
    path: "/application/open-fundamental/financial-report/balance-sheet/accumulated",
    kind: "json",
    description: "Query balance sheet (accumulated)",
  },
  "fundamental.cash-flow": {
    key: "fundamental.cash-flow",
    method: "POST",
    path: "/application/open-fundamental/financial-report/cash-flow-statement/accumulated",
    kind: "json",
    description: "Query cash flow statement (accumulated)",
  },
  "fundamental.cash-flow-quarterly": {
    key: "fundamental.cash-flow-quarterly",
    method: "POST",
    path: "/application/open-fundamental/financial-report/cash-flow-statement/quarterly",
    kind: "json",
    description: "Query cash flow statement (quarterly)",
  },
  "fundamental.main-business": {
    key: "fundamental.main-business",
    method: "POST",
    path: "/application/open-fundamental/main-business",
    kind: "json",
    description: "Query main business composition",
  },
  "fundamental.valuation-analysis": {
    key: "fundamental.valuation-analysis",
    method: "POST",
    path: "/application/open-fundamental/valuation-analysis",
    kind: "json",
    description: "Query valuation analysis",
  },
  "fundamental.top-holders": {
    key: "fundamental.top-holders",
    method: "POST",
    path: "/application/open-fundamental/capital-structure/top-holders",
    kind: "json",
    description: "Query top holders (top10 / top10 float)",
  },
  "fundamental.earning-forecast": {
    key: "fundamental.earning-forecast",
    method: "POST",
    path: "/application/open-fundamental/earning-forecast",
    kind: "json",
    description: "Query earning forecast (consensus estimates)",
  },

  // ─── ai ───
  "ai.knowledge-batch": {
    key: "ai.knowledge-batch",
    method: "POST",
    path: "/application/open-data/ai/search/knowledge/batch",
    kind: "json",
    description: "Batch knowledge search",
  },
  "ai.knowledge-resource.download": {
    key: "ai.knowledge-resource.download",
    method: "GET",
    path: "/application/open-data/ai/resource/download",
    kind: "download",
    description: "Download knowledge resource",
  },
  "ai.security-clue.list": {
    key: "ai.security-clue.list",
    method: "POST",
    path: "/application/open-ai/security-clue/getList",
    kind: "json",
    description: "List security clues",
    pagination: { enabled: true, maxPageSize: 500 },
  },
  "ai.one-pager": {
    key: "ai.one-pager",
    method: "POST",
    path: "/application/open-ai/agent/one-pager",
    kind: "json",
    description: "Generate one pager",
  },
  "ai.investment-logic": {
    key: "ai.investment-logic",
    method: "POST",
    path: "/application/open-ai/agent/investment-logic",
    kind: "json",
    description: "Generate investment logic",
  },
  "ai.peer-comparison": {
    key: "ai.peer-comparison",
    method: "POST",
    path: "/application/open-ai/agent/peer-comparison",
    kind: "json",
    description: "Generate peer comparison",
  },
  "ai.earnings-review.get-id": {
    key: "ai.earnings-review.get-id",
    method: "POST",
    path: "/application/open-ai/agent/earnings-review-getid",
    kind: "json",
    description: "Get earnings review ID",
  },
  "ai.earnings-review.get-content": {
    key: "ai.earnings-review.get-content",
    method: "POST",
    path: "/application/open-ai/agent/earnings-review-getcontent",
    kind: "json",
    description: "Get earnings review content",
  },
  "ai.theme-tracking": {
    key: "ai.theme-tracking",
    method: "POST",
    path: "/application/open-ai/agent/theme-tracking",
    kind: "json",
    description: "Get theme tracking daily report",
  },
  "ai.research-outline": {
    key: "ai.research-outline",
    method: "POST",
    path: "/application/open-ai/agent/research-outline",
    kind: "json",
    description: "Get company research outline",
  },
  "ai.hot-topic": {
    key: "ai.hot-topic",
    method: "POST",
    path: "/application/open-ai/hot-topic/getList",
    kind: "json",
    description: "List hot topic reports",
    pagination: { enabled: true, maxPageSize: 20 },
  },
  "ai.management-discuss-announcement": {
    key: "ai.management-discuss-announcement",
    method: "POST",
    path: "/application/open-ai/management-discuss/from-announcement",
    kind: "json",
    description: "Management discussion from financial reports (half-year/annual)",
  },
  "ai.management-discuss-earnings-call": {
    key: "ai.management-discuss-earnings-call",
    method: "POST",
    path: "/application/open-ai/management-discuss/from-earningsCall",
    kind: "json",
    description: "Management discussion from earnings calls",
  },
  "ai.viewpoint-debate.get-id": {
    key: "ai.viewpoint-debate.get-id",
    method: "POST",
    path: "/application/open-ai/agent/viewpoint-debate-getid",
    kind: "json",
    description: "Get viewpoint debate ID",
  },
  "ai.viewpoint-debate.get-content": {
    key: "ai.viewpoint-debate.get-content",
    method: "POST",
    path: "/application/open-ai/agent/viewpoint-debate-getcontent",
    kind: "json",
    description: "Get viewpoint debate content",
  },

  // ─── vault ───
  "vault.drive.list": {
    key: "vault.drive.list",
    method: "POST",
    path: "/application/open-vault/drive/getList",
    kind: "json",
    description: "List vault drive files",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "vault.drive.download": {
    key: "vault.drive.download",
    method: "GET",
    path: "/application/open-vault/drive/download/file",
    kind: "download",
    description: "Download vault drive file",
  },
  "vault.record.list": {
    key: "vault.record.list",
    method: "POST",
    path: "/application/open-vault/record/getList",
    kind: "json",
    description: "List voice recording transcriptions",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "vault.record.download": {
    key: "vault.record.download",
    method: "GET",
    path: "/application/open-vault/record/download/file",
    kind: "download",
    description: "Download voice recording transcription file",
  },
  "vault.my-conference.list": {
    key: "vault.my-conference.list",
    method: "POST",
    path: "/application/open-vault/my-conference/getList",
    kind: "json",
    description: "List my conferences",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "vault.my-conference.download": {
    key: "vault.my-conference.download",
    method: "GET",
    path: "/application/open-vault/my-conference/download/file",
    kind: "download",
    description: "Download my conference resource",
  },
  "vault.wechat-message.list": {
    key: "vault.wechat-message.list",
    method: "POST",
    path: "/application/open-vault/wechatgroupmsg/list",
    kind: "json",
    description: "List WeChat group messages",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  "vault.wechat-chatroom.list": {
    key: "vault.wechat-chatroom.list",
    method: "POST",
    path: "/application/open-vault/wechatgroupmsg/chatroomId",
    kind: "json",
    description: "List WeChat group chatroom IDs",
  },
}
