export interface EndpointDefinition {
  key: string
  method: "GET" | "POST"
  path: string
  kind: "json" | "download"
  description: string
  pagination?: {
    enabled: true
    maxPageSize: number
  }
}

export const ENDPOINTS = {
  authLogin: {
    key: "auth.login",
    method: "POST",
    path: "/application/auth/oauth/open/loginV2",
    kind: "json",
    description: "Get access token",
  },

  lookupResearchAreas: {
    key: "lookup.research-areas.list",
    method: "GET",
    path: "/guide/research-area-local",
    kind: "json",
    description: "List research areas from local docs",
  },
  lookupBrokerOrgs: {
    key: "lookup.broker-orgs.list",
    method: "GET",
    path: "/guide/broker-orgs-local",
    kind: "json",
    description: "List broker orgs from local docs",
  },
  lookupMeetingOrgs: {
    key: "lookup.meeting-orgs.list",
    method: "GET",
    path: "/guide/meeting-orgs-local",
    kind: "json",
    description: "List meeting orgs from local docs",
  },
  lookupIndustries: {
    key: "lookup.industries.list",
    method: "GET",
    path: "/guide/industries-local",
    kind: "json",
    description: "List industries from local docs",
  },
  lookupRegions: {
    key: "lookup.regions.list",
    method: "GET",
    path: "/guide/regions-local",
    kind: "json",
    description: "List regions from local docs",
  },
  lookupAnnouncementCategories: {
    key: "lookup.announcement-categories.list",
    method: "GET",
    path: "/guide/announcement-categories-local",
    kind: "json",
    description: "List announcement categories from local docs",
  },
  lookupIndustryCodes: {
    key: "lookup.industry-codes.list",
    method: "GET",
    path: "/guide/industry-codes-local",
    kind: "json",
    description: "List Shenwan industry codes from local docs",
  },
  lookupThemeIds: {
    key: "lookup.theme-ids.list",
    method: "GET",
    path: "/guide/theme-ids-local",
    kind: "json",
    description: "List theme IDs from local docs",
  },

  insightOpinionList: {
    key: "insight.opinion.list",
    method: "POST",
    path: "/application/open-insight/chief-opinion/getList",
    kind: "json",
    description: "List chief opinions",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightSummaryList: {
    key: "insight.summary.list",
    method: "POST",
    path: "/application/open-insight/summary/v2/getList",
    kind: "json",
    description: "List summaries",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightSummaryDownload: {
    key: "insight.summary.download",
    method: "GET",
    path: "/application/open-insight/summary/v2/download/file",
    kind: "download",
    description: "Download summary file",
  },
  insightRoadshowList: {
    key: "insight.roadshow.list",
    method: "POST",
    path: "/application/open-insight/schedule/roadshow/getList",
    kind: "json",
    description: "List roadshows",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightSiteVisitList: {
    key: "insight.site-visit.list",
    method: "POST",
    path: "/application/open-insight/schedule/site-visit/getList",
    kind: "json",
    description: "List site visits",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightStrategyList: {
    key: "insight.strategy.list",
    method: "POST",
    path: "/application/open-insight/schedule/strategy-meeting/getList",
    kind: "json",
    description: "List strategy meetings",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightForumList: {
    key: "insight.forum.list",
    method: "POST",
    path: "/application/open-insight/schedule/forum/getList",
    kind: "json",
    description: "List forums",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightResearchList: {
    key: "insight.research.list",
    method: "POST",
    path: "/application/open-insight/broker-report/getList",
    kind: "json",
    description: "List broker research reports",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightResearchDownload: {
    key: "insight.research.download",
    method: "GET",
    path: "/application/open-insight/broker-report/download/file",
    kind: "download",
    description: "Download broker research report",
  },
  insightForeignReportList: {
    key: "insight.foreign-report.list",
    method: "POST",
    path: "/application/open-insight/foreign-report/getList",
    kind: "json",
    description: "List foreign reports",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightForeignReportDownload: {
    key: "insight.foreign-report.download",
    method: "GET",
    path: "/application/open-insight/foreign-report/download/file",
    kind: "download",
    description: "Download foreign report",
  },
  insightAnnouncementList: {
    key: "insight.announcement.list",
    method: "POST",
    path: "/application/open-insight/announcement/getList",
    kind: "json",
    description: "List announcements",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  insightAnnouncementDownload: {
    key: "insight.announcement.download",
    method: "GET",
    path: "/application/open-insight/announcement/download/file",
    kind: "download",
    description: "Download announcement file",
  },

  quoteDayKline: {
    key: "quote.day-kline",
    method: "POST",
    path: "/application/open-quote/kline/daily",
    kind: "json",
    description: "Query A-share daily kline (SH/SZ/BJ)",
  },
  quoteDayKlineHk: {
    key: "quote.day-kline-hk",
    method: "POST",
    path: "/application/open-quote/kline-hk/daily",
    kind: "json",
    description: "Query HK stock daily kline (HK)",
  },
  fundamentalIncomeStatement: {
    key: "fundamental.income-statement",
    method: "POST",
    path: "/application/open-fundamental/financial-report/income-statement/accumulated",
    kind: "json",
    description: "Query income statement (accumulated)",
  },
  fundamentalBalanceSheet: {
    key: "fundamental.balance-sheet",
    method: "POST",
    path: "/application/open-fundamental/financial-report/balance-sheet/accumulated",
    kind: "json",
    description: "Query balance sheet (accumulated)",
  },
  fundamentalCashFlow: {
    key: "fundamental.cash-flow",
    method: "POST",
    path: "/application/open-fundamental/financial-report/cash-flow-statement/accumulated",
    kind: "json",
    description: "Query cash flow statement (accumulated)",
  },
  fundamentalMainBusiness: {
    key: "fundamental.main-business",
    method: "POST",
    path: "/application/open-fundamental/main-business",
    kind: "json",
    description: "Query main business composition",
  },
  fundamentalValuationAnalysis: {
    key: "fundamental.valuation-analysis",
    method: "POST",
    path: "/application/open-fundamental/valuation-analysis",
    kind: "json",
    description: "Query valuation analysis",
  },

  aiKnowledgeBatch: {
    key: "ai.knowledge-batch",
    method: "POST",
    path: "/application/open-data/ai/search/knowledge/batch",
    kind: "json",
    description: "Batch knowledge search",
  },
  aiKnowledgeResource: {
    key: "ai.knowledge-resource.download",
    method: "GET",
    path: "/application/open-data/ai/resource/download",
    kind: "download",
    description: "Download knowledge resource",
  },
  aiSecurityClue: {
    key: "ai.security-clue.list",
    method: "POST",
    path: "/application/open-ai/security-clue/getList",
    kind: "json",
    description: "List security clues",
    pagination: { enabled: true, maxPageSize: 500 },
  },
  aiOnePager: {
    key: "ai.one-pager",
    method: "POST",
    path: "/application/open-ai/agent/one-pager",
    kind: "json",
    description: "Generate one pager",
  },
  aiInvestmentLogic: {
    key: "ai.investment-logic",
    method: "POST",
    path: "/application/open-ai/agent/investment-logic",
    kind: "json",
    description: "Generate investment logic",
  },
  aiPeerComparison: {
    key: "ai.peer-comparison",
    method: "POST",
    path: "/application/open-ai/agent/peer-comparison",
    kind: "json",
    description: "Generate peer comparison",
  },
  aiEarningsReviewGetId: {
    key: "ai.earnings-review.get-id",
    method: "POST",
    path: "/application/open-ai/agent/earnings-review-getid",
    kind: "json",
    description: "Get earnings review ID",
  },
  aiEarningsReviewGetContent: {
    key: "ai.earnings-review.get-content",
    method: "POST",
    path: "/application/open-ai/agent/earnings-review-getcontent",
    kind: "json",
    description: "Get earnings review content",
  },
  aiThemeTracking: {
    key: "ai.theme-tracking",
    method: "POST",
    path: "/application/open-ai/agent/theme-tracking",
    kind: "json",
    description: "Get theme tracking daily report",
  },
  aiResearchOutline: {
    key: "ai.research-outline",
    method: "POST",
    path: "/application/open-ai/agent/research-outline",
    kind: "json",
    description: "Get company research outline",
  },
  aiHotTopic: {
    key: "ai.hot-topic",
    method: "POST",
    path: "/application/open-ai/hot-topic/getList",
    kind: "json",
    description: "List hot topic reports",
    pagination: { enabled: true, maxPageSize: 20 },
  },
  aiManagementDiscussAnnouncement: {
    key: "ai.management-discuss-announcement",
    method: "POST",
    path: "/application/open-ai/management-discuss/from-announcement",
    kind: "json",
    description: "Management discussion from financial reports (half-year/annual)",
  },
  aiManagementDiscussEarningsCall: {
    key: "ai.management-discuss-earnings-call",
    method: "POST",
    path: "/application/open-ai/management-discuss/from-earningsCall",
    kind: "json",
    description: "Management discussion from earnings calls",
  },
  aiViewpointDebateGetId: {
    key: "ai.viewpoint-debate.get-id",
    method: "POST",
    path: "/application/open-ai/agent/viewpoint-debate-getid",
    kind: "json",
    description: "Get viewpoint debate ID",
  },
  aiViewpointDebateGetContent: {
    key: "ai.viewpoint-debate.get-content",
    method: "POST",
    path: "/application/open-ai/agent/viewpoint-debate-getcontent",
    kind: "json",
    description: "Get viewpoint debate content",
  },
  quoteMinuteKline: {
    key: "quote.minute-kline",
    method: "POST",
    path: "/application/open-quote/kline/minute",
    kind: "json",
    description: "Query A-share minute kline (SH/SZ/BJ)",
  },
  fundamentalIncomeStatementQuarterly: {
    key: "fundamental.income-statement-quarterly",
    method: "POST",
    path: "/application/open-fundamental/financial-report/income-statement/quarterly",
    kind: "json",
    description: "Query income statement (quarterly)",
  },
  fundamentalCashFlowQuarterly: {
    key: "fundamental.cash-flow-quarterly",
    method: "POST",
    path: "/application/open-fundamental/financial-report/cash-flow-statement/quarterly",
    kind: "json",
    description: "Query cash flow statement (quarterly)",
  },
  vaultDriveList: {
    key: "vault.drive.list",
    method: "POST",
    path: "/application/open-vault/drive/getList",
    kind: "json",
    description: "List vault drive files",
    pagination: { enabled: true, maxPageSize: 50 },
  },
  vaultDriveDownload: {
    key: "vault.drive.download",
    method: "GET",
    path: "/application/open-vault/drive/download/file",
    kind: "download",
    description: "Download vault drive file",
  },
} as const satisfies Record<string, EndpointDefinition>

export const ENDPOINT_REGISTRY: Record<string, EndpointDefinition> = Object.values(ENDPOINTS).reduce<Record<string, EndpointDefinition>>((accumulator, endpoint) => {
  accumulator[endpoint.key] = endpoint
  return accumulator
}, {})
