// Reads version from package.json and writes to src/version.ts
// Called automatically by npm prepack hook before publish
import { readFileSync, writeFileSync } from "node:fs"
import { resolve, dirname } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkg = JSON.parse(readFileSync(resolve(__dirname, "../package.json"), "utf8"))
const version = pkg.version

const content = `// Auto-generated by scripts/version.ts — DO NOT EDIT\nexport const CLI_VERSION = "${version}"\n`
writeFileSync(resolve(__dirname, "../src/version.ts"), content, "utf8")
console.log(`src/version.ts updated to ${version}`)